### ISSUE TITLE
Shark Damage is not representative of Config Values

### ISSUE THREAD

**Issue by Darkosto** [tristankechlo/Living-Things#14]
**Describe the bug**
Shark Damage is very high and unable to be altered in Config. The health is also unable to be changed. It looks like the values may not be properly hooked into the config.

**To Reproduce**
1. Set shark to 1 damage
2. Go to shark
3. Die to shark in 1-2 hits
4. Yell a lot!

**Expected behavior**
Shark health and damage to be changed by config

**Screenshots**

**Additional context**

Shark Health
```
.createMutableAttribute(Attributes.MAX_HEALTH, LivingThingsConfig.SHARK.health.get())
```

Thanks!

**Comment by tristankechlo** [comment]
thanks for mentioning ;D

**Comment by tristankechlo** [comment]
not yet stated in the config, but the health-attribute only affects newly spawned mobs
