### ISSUE TITLE
NoClassDefinedError on 1.16.3-1.2.1 on server

### ISSUE THREAD

**Issue by kreezxil** [tristankechlo/Living-Things#15]
Issue:  livingthings-1.16.3-1.2.1 crashes dedicated server Forge 1.16.3 build 34.1.25

Notes:
     failed to load correctly, NoClassDefFoundError, probably trying to load client side classes on a dedicated server.

crash report: 
http://paste.ubuntu.com/p/cSXrmmZKw9/

fml server latest: 
http://paste.ubuntu.com/p/wy4YWcNXyx/

**Comment by tristankechlo** [comment]
yes, exactly what you mentioned
should be fixed in 1.2.2
