### ISSUE TITLE
games crashes when starting

### ISSUE THREAD

**Issue by dogs1212** [tristankechlo/Living-Things#17]
The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Failed to load description for particle livingthings:arrow_up_green
Exit Code: -1

**Comment by tristankechlo** [comment]
first, not that much of a helpful bug report
 - What mod version do you use?
 - What forge version do you use?
 - Crash report?

second, someone else already reported the same issue previously
 - not the fault of my mod particular
 - it seems there are some incompatibilities between my mod and others

and yeah, i'll probably remove my custom particles
