### ISSUE TITLE
[1.16.4] Server overload

### ISSUE THREAD

**Issue by nanonestor** [tristankechlo/Living-Things#20]
**Describe the bug**
Unfortunately my modpack when run on a dedicated server seems to have serious mob loading errors (or something, i'm shaky on terms) - When world is loaded and has a player client connected living things mobs appear to bog down the server causing around 10,000ms to 20,000ms behind errors

> [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 11301ms or 226 ticks behind

It does not show console log or debug log messages about this however:

-Running the Spark [https://www.curseforge.com/minecraft/mc-mods/spark](url) mod to analyze activity (I believe?) shows a high amount of activity from living creatures --> [https://spark.lucko.me/#H9vS7xEx9H](url)

**To Reproduce**
Dedicated Server 1.16.4
Forge 35.0.17
Living Things 1.2.3

(My modpack [https://www.curseforge.com/minecraft/modpacks/the-briar-patch](url))

**Expected behavior**
Reasonable server loading due to living things mobs.

**Screenshots**

**Additional context**

After removing the mod and rebooting the server the following logs produce:
latest.log [https://pastebin.com/b5MGYsN8](url)
debug log (see attatched)
[debug (8).log](https://github.com/tristankechlo/Living-Things/files/5572219/debug.8.log)

After rebooting the server several times the messages about skipping living things entities continue... for awhile...  eventually i did a /kill command for all and now the server has stopped with the ticks behind entirely.

**Comment by tristankechlo** [comment]
Does your server has enough RAM allocated?
Spark seems to be only for 1.15.2 (don't know if that's a problem)
Did you test it with a special version of your modpack, because I couldn't start a server with the newest version from curseforge(some mods require 1.16.3 and won't work on 1.16.4)

**Comment by nanonestor** [comment]
Spark makes you download the latest version from their website rather than Curseforge (i just found out about this mod - its awesome lol) [https://ci.lucko.me/job/spark/](url) The 'Forge' version there worked fine.

If downloading the pack I made when you create a server and dump in the mods you need to leave out the Horse Stats mod "horsestatsmod-MC1.16.x-1.3.3.jar" - that's the only client side only mod present right now I believe.  Forge a few versions ago changed to allow 1.16.3 mods to load on 1.16.4.

**Comment by tristankechlo** [comment]
ok, I will run some test to see what happens
 <br><br>
> Forge a few versions ago changed to allow 1.16.3 mods to load on 1.16.4

a small side note: a mod has to specify on which version they shall be loaded, nothing to do with forge

**Comment by nanonestor** [comment]
Rgr - I do have a backup save of the last world with this issue, I could get it to you if you would like.

**Comment by tristankechlo** [comment]
So after running quite a lot tests, I don't think any of my mobs are causing these issues.
I could see some minor performance issues when I spawned a very large amount of mobs, but there wasn't any differences if they were vanilla mobs or from my mod.
So what I think right now is, that your server has not enough RAM to handle your modpack

**Comment by nanonestor** [comment]
Ok, well I'll drop your mod from my modpack for now then.  Again if you would like a copy of one of the worlds with this issue i'd be happy to send it with a drop box or something.  When this mod and its' entities were removed from the world it went from being 12,000ms behind to running fine.  It was like I'd done an exorcism.

**Comment by tristankechlo** [comment]
I literally spawned ~50 mobs of each type at the same time and the server didn't skip a single tick

Aside from that your modpack contains multiple mods which won't do anything on the server side, and only use unnecessary memory.

**Comment by nanonestor** [comment]
Yeah I had to leave alot of the client side mods on server side because they aren't configured correctly to show modlist match compatibility with servers. Horse stats guy figured it out though. 

When I removed living things itcycled through error warnings of 1000's of mobs being removed.
