### ISSUE TITLE
Bug: Suppressing spawn of cod, salmon squid

### ISSUE THREAD

**Issue by mactso** [tristankechlo/Living-Things#21]
We noticed there were no cod, salmon, or squid after installing this mod.
Minecraft: 1.16.3, 1.16.4
Forge: Latest version for both.
Seed: -6740266957699037741
X,Z: -1000,-750

**To Reproduce**
Set up Minecraft 1.16.3 or 1.16.4 (same under both) profile (quick and easy with overwolf)
Run it and find an ocean.
/kill @e[type=!Player]
Wait 30 seconds for respawns
/tp @e @p
Observe there are quite a few fish (cod, dolphin) and squid (plus skeletons etc.)
At this location there were no salmon (see below)
You could alternatively 
/tp @e[type=cod] @p
/tp @e[type=salmon] @p
/tp @e[type=squid] @p

Install more living things
Run it again.
Repeat the above procedure.
Sometimes there will be 1 to a few cod.  Sometimes there will be none at all.
Same for squid.  

Travel to cold ocean at -1050,-850.
Repeat.
Observe dolphins and salmon present without mod and mostly missing (sometimes entirely missing) with the mod.

Only affects passive mobs.  Does not affect hostile mobs added by other mods for example.

Cheers!

**Comment by mactso** [comment]
FYI: I lowered the spawn rates for sharks, manta rays, and crabs to 5 and it had no effect.
And I got no cod,salmon,dolphin, or squid at all the next test tho I did see fewer manta rays.

**Comment by tristankechlo** [comment]
yeah I know about that, the spawn-weights are a little bit to high
setting them down should fix it, but the changes are only affective after a client/server restart

**Comment by mactso** [comment]
That's the odd thing, a spawn weight of 10 doesn't seem crazy high.  The crabs maybe but not the sharks and mantaray.  Anyway- I turned them down and it's better but the cod, salmon, and squid numbers are still way down.    
Cheers!
