### ISSUE TITLE
Additional Stat: Sight Range

### ISSUE THREAD

**Issue by Tyrius1** [tristankechlo/Living-Things#22]
**Is your feature request related to a problem? Please describe.**
Not really a problem but I do feel the baby ender dragons sight range is abnormally short.

**Describe the solution you'd like**
A config to tweak sight/follow range to fit  the pack devs/players desired play style.

**Describe alternatives you've considered**
I tried using the mod farsighted but baby ender dragon don't seem to be effected by it.

**Additional context**
Thank you for porting to 1.18.2 :)

**Comment by tristankechlo** [comment]
Interesting idea, will see what I can do

**Comment by tristankechlo** [comment]
this should be implemented with the newest mod-version 2.1.0
