### ISSUE TITLE
modifying m config file for a server

### ISSUE THREAD

**Issue by chawry** [tristankechlo/Living-Things#23]
**Describe the bug**
i have tried manually modifying the condig file  and the consolechange i
 Incorrect key Giraffe.CanBeRidden was corrected from true to its default, null. 
**To Reproduce**

**Expected behavior**
will apply the settings mob config for the giraffe to be rideable

**Comment by tristankechlo** [comment]
giraffes are not ridable, so the key is removed from the config

**Comment by chawry** [comment]
is it possible to allow this for any mobs through the config file?

**Comment by tristankechlo** [comment]
no, you can only change the options that are already in the config
you can not add more, I would have to implement it in the code

**Comment by tristankechlo** [comment]
so the only ridable mobs at the moment are ostrich and tamed elephants

**Comment by chawry** [comment]
thank you for answering , can you please do that as my friends in our server is requesting for it

**Comment by tristankechlo** [comment]
can't say for sure, but probably not

**Comment by chawry** [comment]
aw too bad, but we did really enjoy your mod
