### ISSUE TITLE
CRASH 1.19.2 Caused by: java.lang.IllegalArgumentException: No model for layer livingthings:ancientarmormodel#main

### ISSUE THREAD

**Issue by Minebrah** [tristankechlo/Living-Things#25]
livingthings-forge-1.19.2-2.0.0-rc1

https://gist.github.com/Minebrah/cf51b3de9377752a1ef11513aa74f0cd

**Comment by tristankechlo** [comment]
Do you have any other mods installed?  
In the log I only see optifine (I think this is an older version too)

**Comment by tristankechlo** [comment]
closed due to inactivity
