### ISSUE TITLE
Creatures do not spawn.

### ISSUE THREAD

**Issue by Rogenar** [tristankechlo/Living-Things#26]
### What happened?

In livingthings-fabric-1.20.1-2.0.0, living things don't spawn around. I guess it's a mod incompatibility.

### Minecraft Version

1.20.1

### Modversion

1.20.1 2.0.0

### Modloader

Fabric

### Additional context

[latest.log](https://github.com/tristankechlo/LivingThings/files/12308274/latest.log)

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Yeah, you got a lot of mods there (677).  
I am not sure which mod might cause the incompatibility.  
FYI, there is at least one mod that's causing a huge amount of errors in the log files

**Comment by Rogenar** [comment]
How do I find out which one is causing it?

**Comment by tristankechlo** [comment]
Usually, to find a mod that's making problems, the best way is to remove all mods and re-add them one by one.  
This way you know the mod, when the error re-appears.  
But with that many mods it might take some time.
