### ISSUE TITLE
[Bug]: Elephant and Ostriches Can't "Move"

### ISSUE THREAD

**Issue by NoobWithAUniqueName** [tristankechlo/Living-Things#27]
### What happened?

Ostriches and Elephants aren't knocked back when hit and can not move on their own. Using leads on them do not work either. I removed all mods except Exordium, Sodium, and Living Things and the issue is still present.

### Minecraft Version

1.20.1

### Modversion

1.20.1 - 2.0.0 - Fabric

### Modloader

Fabric

### Additional context

Video:
https://github.com/tristankechlo/LivingThings/assets/138097838/2da10727-700b-4f7d-b814-d64c95a03166

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Thank you for reporting this, I will look into this later.  
Do you have access to the log files? Are there any errors regarding this?  
I also noticed in the video that the tusks from the elephant are kinda messed up, need to look at that too

**Comment by tristankechlo** [comment]
Found the bug for the not-walking-problem, consist for 1.19.4 too.  
Will be fixed with the next update.

**Comment by NoobWithAUniqueName** [comment]
Nice! Ty for your work

**Comment by tristankechlo** [comment]
should be fixed with the newest modversion (2.0.1)
