### ISSUE TITLE
[Bug]: Server Crash with Mantaray

### ISSUE THREAD

**Issue by andw20** [tristankechlo/Living-Things#31]
### What happened?

The server died due to Ticking Entity caused by the mob Mantaray. 

Crash log
[crash-2023-08-20_16.48.03-server.txt](https://github.com/tristankechlo/LivingThings/files/12388688/crash-2023-08-20_16.48.03-server.txt)

Latest log
[latest.log](https://github.com/tristankechlo/LivingThings/files/12388689/latest.log)

### Minecraft Version

1.20.1

### Modversion

Fabric 1.20.1 - 2.0.1

### Modloader

Fabric

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
should be fixed with the newest modversion (2.0.2)
