### ISSUE TITLE
[Bug]: following/teleporting

### ISSUE THREAD

**Issue by harambens** [tristankechlo/Living-Things#32]
### What happened?

my monkeys keep teleporting to me even when i sit them down. I don't want them teleporting to me wherever I go.
Other tamed creatures stay put when sat down

### Minecraft Version

1.20.1

### Modversion

Fantasy MC Fabric

### Modloader

Fabric

### Additional context

This mod is in a modpack which could affect it

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by harambens** [comment]
I've put the monkeys in boats so i guess i resolved it lol

**Comment by tristankechlo** [comment]
What exact version has the mod?  
1.20.1-2.0.2 or something else?

**Comment by harambens** [comment]
1.20.1 im pretty sure

**Comment by tristankechlo** [comment]
a fix of this will be included in the next update, currently working on fixing this for all versions

**Comment by tristankechlo** [comment]
this should be fixed with the newest released version 2.1.0
