### ISSUE TITLE
[Bug]: crashing on 1.20.1 forge 

### ISSUE THREAD

**Issue by Thunderrock424242** [tristankechlo/Living-Things#34]
### What happened?

loading my modpack caused living things to crash

### Minecraft Version

1.20.1

### Modversion

2.0.2

### Modloader

Forge

### Additional context

[latest.log](https://github.com/user-attachments/files/16020026/latest.log)

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Not sure what caused the crash, but here are a few points that might have something to do with it:

1. You started a Forge client, but there are a few NeoForge mods present. I don't now how compatible these are.
2. One mod failed to load completely `[27Jun2024 14:33:24.444] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: extra_compat, class net.cyber_rat.extra_compat.ExtraCompat`
It looks like Forge never started correctly after this error.
3. It seems like there are several conflicts in mixins between some mods. Not sure how well these conflicts are handled.

Again, maybe these are the cause of the crash or maybe not.  
  
Does the modpack load when LivingThings is removed?  
Is the modpack public, so I can run some tests myself?
