### ISSUE TITLE
[Bug]: Peacock Audio is Stereo instead of Mono

### ISSUE THREAD

**Issue by EngineOfDarkness** [tristankechlo/Living-Things#47]
### What happened?

The .ogg files for the peacock are all in Stereo - this leads to the sound not being positioned correctly (I have setup OpenAL to output to 5.1 and this works correctly with other entities of this mod).

It also causes this sound to not be processed correctly by Sound Physics.

### Minecraft Version

1.21.1

### Modversion

livingthings-neoforge-1.21.1-2.1.0.jar

### Modloader

NeoForge

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Yeah, you are right. Not sure how I missed that.
Just in time with the bug-report, I am currently working on some bugfixes for this mod 👍

**Comment by tristankechlo** [comment]
this issue should be fixed with the newest modversion (2.1.1)
