### ISSUE TITLE
[Bug]: ATM10 1.0 with Living Things added doesn't allow players to connect to a server through a Velocity Proxy

### ISSUE THREAD

**Issue by LevyWilson** [tristankechlo/Living-Things#48]
### What happened?

I run a ATM10 server through a Velocity proxy. We recently tried updating to 1.0 of ATM10 and we couldn't connect to the server. I started disabling the new mods in the pack and once I disabled Living Things, we could connect again. We're now on ATM10 1.1 without Living Things and we have no issues. Here is the Latest log from the Velocity proxy logs. https://gist.github.com/LevyWilson/f5471171010818d65d1ca7ba62dc6d5b

### Minecraft Version

1.21.1

### Modversion

livingthings-neoforge-1.21.1-2.1.2.jar

### Modloader

NeoForge

### Additional context

Using Velocity 3.4.0 Snapshot 439

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Thank you for the report, the log hints at something related to command arguments.
I will have a look at this, will see what I can do

**Comment by tristankechlo** [comment]
Did you modify the modpack in any way? Added/removed mods, changed some configs?

**Comment by LevyWilson** [comment]
> Did you modify the modpack in any way? Added/removed mods, changed some configs?

The ATM10 modpack was given Neoforwarding at first, now it's running with Proxy Compatible Forge. Those two are the mods that specifically do cross-stitching of commands, so it might be related to those. The error occurs with either one installed. For my purposes they both do the same thing. I am using just PCF right now though. I'm also using a neoforge port of Bungeeforge to make Bungeecord work for merging the chats of all my servers. Then there's Performant, a mod that adds a bunch of performance fixes for servers. Don't see how that would effect this mod.

**Comment by p0t4t0sandwich** [comment]
I did some debug logging with PCF, and interestingly enough, found the, well, wouldn't say "problem", more just "oh wow someone did something properly".
You're mixining in to register your command type in vanilla's `BuiltInRegistries.COMMAND_ARGUMENT_TYPE`, which is great, except you're the only mod that does it lol.
PCF sends Vanilla `ArgumentType`s normally (getting them from said registry), and has some extra logic for whenever that registry returns `null` (ie, wrapping modded command arguments so Velocity doesn't throw a fit).
Nothing you need to do on your end, I'll think of an extensible way to register/detect mods that register their argument types.

**Comment by p0t4t0sandwich** [comment]
Seems that was only half the issue, for some reason the `minecraft:entities` argument needs to be wrapped as well. Got it all sorted now though.

**Comment by tristankechlo** [comment]
Thank your for the extensive debugging and testing 👍 

Not sure if that's relevant, but I decided to remove the mixin completely. The command, I am using the custom argument type with, can be built without it pretty easily. It was more of test to see if it would make things easier to code.
If I remember right, that argument type caused problems with other mods too.
