### ISSUE TITLE
[Enhancement]: Nether Knight loots are unbalanced

### ISSUE THREAD

**Issue by Franco227** [tristankechlo/Living-Things#49]
### What is your idea?

The Nether Knight currently always drops a Netherite Axe AND a Netherite Sword, enchanted with Sharpness II + Efficiency I/II/III for the axe, and Sharpness II/III/IV + Looting I for the sword.
Despite the Nether Knight's high health and damage, it is easily beatable by towering up, blocking its path or putting it in a boat, giving these rare loots for basically free.
On top of that, this mob isn't very rare, so you quickly end up with a bunch of swords and axe, making it too overpowered.

My suggestion is that either the Nether Knight should be massively buffed (more health, and maybe a ranged attack) and its spawn rate nerfed, either its weapons shouldn't drop 100% of the time. With its current spawn rate and statistics, a 25% chance for each weapon to drop sounds more reasonable than the current 100% chance for both.

**Comment by tristankechlo** [comment]
The dropchance for the weapons can be adjusted through the config.  
Inside `./minecraft/config/livingthings/nether_knight.json` you can set the value `weaponDropChance` to a lower chance.  
The value will be used for both weapons.

**Comment by tristankechlo** [comment]
But as you suggested, I will probably lower the default value that is used while generating a new config.

**Comment by Franco227** [comment]
I wasn't aware of the config, that solves my issue. After a bit of testing, these values looks fairly balanced to me :
```json
"canAttack": true,
"health": 250.0,
"movementSpeed": 0.26,
"attackDamage": 10.0,
"weaponDropChance": 33.3,
"spawning": {
    "spawnWeight": 5,
    "minSpawnCount": 1,
    "maxSpawnCount": 1
}
```

**Comment by tristankechlo** [comment]
I chose those values as default values:  
health: 180 (90 hearts)  
drop chance: 15%  
spawn weight: 15  

currently releasing these changes across all the versions
