### ISSUE TITLE
[Feature]: Add Foods Tag

### ISSUE THREAD

**Issue by TheBedrockMaster** [tristankechlo/Living-Things#50]
### What is your idea?

Add the `c:foods` item tag to edible items - 1.21.1 Neoforge.

**Comment by tristankechlo** [comment]
Yes, can do that. Is there anything special that will benefit from it.

Sitenote mostly to myself:
~~Since Forge now also moved their tags to the `c` namespace, I will be reworking the tags for all 1.21.2+ versions~~  
The item tags could need a rework accross all currently released mod-versions.
