### ISSUE TITLE
crash livingthings : arrow_up

### ISSUE THREAD

**Issue by YannoteX** [tristankechlo/Living-Things#8]
A crash when I start the game (1.16.3) with the latest version.
This is what it says : 
           The game crashed whilst rendering overlay
           Error: java.lang.IllegalStateException: Failed to load description for particle livingthings:arrow_up
           Exit Code: -1

Just start the game with 1.16.3 forge 34.1.0 version

**Comment by YannoteX** [comment]
Nevermin it was an other mod sorry.

**Comment by tristankechlo** [comment]
Do you now which mod? I'm just curious.

**Comment by YannoteX** [comment]
Furenzu
